
"""The main module that runs the game."""

import curses
import random
import logging

from argparser import Arguments
from pieces import read_pieces
from gui import GameWindow
from grid import Grid
from utils import generate_seed

logger = logging.getLogger(__name__)

# to manage screen display
COLS = 10
ROWS = 10
MARGIN = 20
START_POS = (0, COLS // 2 - 1)

window: curses.window = curses.initscr()

def game_loop(log_set: bool):
    """The main game loop that runs until the game is over."""
    pieces = read_pieces('pieces')
    grid = Grid(ROWS, COLS, log_set)
    block_char = '█'
    gui = GameWindow(window, MARGIN, log_set, block_char)

    current_piece = random.choice(pieces)
    if(log_set):
        logger.info("Generated piece %s", current_piece)

    while True:
        position = list(START_POS)
        next_piece = random.choice(pieces)
        if(log_set):
            logger.info("Generated next piece %s", next_piece)
        gui.update_window(grid.matrix, next_piece)
        can_move_piece = grid.can_move(current_piece, tuple(position), 'b')

        if not can_move_piece:
            if log_set:
                logger.info("No more moves available, game over")
            break

        while can_move_piece:
            grid.put_piece(current_piece, tuple(position))
            grid.matrix, cleared_lines = grid.clear_filled_lines()
            gui.update_window(grid.matrix, next_piece)
            window.refresh()

            if cleared_lines > 0:
                can_move_piece = False
                gui.score += cleared_lines
                if log_set:
                    logger.info("Score updated to %s", gui.score)
                continue

            current_piece = gui.handle_key_events(position, current_piece, next_piece, grid)
            can_move_piece = grid.can_move(current_piece, tuple(position), 'b')
            if can_move_piece:
                grid.remove_piece(current_piece, tuple(position))
                position[0] += 1
                window.clear()

        gui.clear_piece(next_piece, (10, ROWS // 2))
        current_piece = next_piece


def main(stdscr: curses.window):
    """The main function that initializes the game."""
    
    arguments = Arguments()
    arguments.parse_arguments()
    if arguments.is_log_set:
        logging.basicConfig(filename=arguments.log_path, level=logging.INFO, filemode='w')
    else:
        logging.basicConfig(filename='game.log', level=logging.INFO, filemode='w')
    logger.info("Starting the game")
    if arguments.is_seed_set:
        random.seed(arguments.seed)
        logger.info("Seed set by user to %s", arguments.seed)
    else:
        seed = generate_seed()
        random.seed(seed)
        if arguments.is_log_set:
            logger.info("Seed generated by system is %s", seed)

    curses.curs_set(0)
    curses.noecho()
    curses.cbreak()
    stdscr.keypad(True)
    stdscr.nodelay(True)

    game_loop(arguments.is_log_set)

    curses.curs_set(1)
    curses.echo()
    curses.nocbreak()
    stdscr.keypad(False)

curses.wrapper(main)
