sonar.projectKey=ferhat-ramdani_tetris
sonar.organization=ferhat-ramdani

# Tell Sonar to look at your Python files
sonar.sources=.
sonar.exclusions=tests/**, venv/**, .pytest_cache/**
sonar.language=py
sonar.python.version=3
