
"""The main module that runs the game."""

import curses
import random
import logging

from argparser import Arguments
from pieces import read_pieces
from gui import GameWindow
from grid import Grid
from utils import generate_seed

logger = logging.getLogger(__name__)

# to manage screen display
COLS = 10
ROWS = 20
MARGIN = 20

window: curses.window = curses.initscr()

def game_loop(log_set: bool,
              pieces_folder: str,
              speed: str,
              width: int,
              height: int
              ):
    """The main game loop that runs until the game is over."""
    pieces = read_pieces(pieces_folder)
    grid = Grid(height, width, log_set)
    gui = GameWindow(window, MARGIN, log_set, speed)

    current_piece = random.choice(pieces)
    if log_set:
        logger.info("Generated piece %s", current_piece)

    while True:
        position = list((0, width // 2 - 1))
        next_piece = random.choice(pieces)
        if log_set:
            logger.info("Generated next piece %s", next_piece)
        can_move_piece = grid.can_move(current_piece, tuple(position), 'b')

        if not can_move_piece:
            if log_set:
                logger.info("No more moves available, game over")
            break

        while can_move_piece:
            grid.put_piece(current_piece, tuple(position))
            gui.update_window(grid.matrix, next_piece)

            current_piece = gui.handle_key_events(position, current_piece, next_piece, grid)
            can_move_piece = grid.can_move(current_piece, tuple(position), 'b')
            if can_move_piece:
                grid.remove_piece(current_piece, tuple(position))
                position[0] += 1

        grid.matrix, cleared_lines = grid.clear_filled_lines()

        if cleared_lines > 0:
            can_move_piece = False
            gui.score += cleared_lines
            gui.cleared_lines += cleared_lines
            gui.speed_value += 1
            if log_set:
                logger.info("Score updated to %s", gui.score)
            gui.update_window(grid.matrix, next_piece)

        gui.clear_piece(next_piece, (10, ROWS // 2))
        current_piece = next_piece

def main(stdscr: curses.window):
    """The main function that initializes the game."""

    arguments = Arguments()
    arguments.parse_arguments()
    if arguments.is_log_set:
        logging.basicConfig(filename=arguments.log_path, level=logging.INFO, filemode='w')
    else:
        logging.basicConfig(filename='game.log', level=logging.INFO, filemode='w')
    logger.info("Starting the game")
    if arguments.is_seed_set:
        random.seed(arguments.seed)
        logger.info("Seed set by user to %s", arguments.seed)
    else:
        seed = generate_seed()
        random.seed(seed)
        if arguments.is_log_set:
            logger.info("Seed generated by system is %s", seed)
    width = COLS
    height = ROWS
    if arguments.width:
        width = arguments.width

    if arguments.height:
        height = arguments.height

    curses.start_color()
    curses.init_pair(1, curses.COLOR_BLUE, curses.COLOR_BLACK)
    curses.init_pair(2, curses.COLOR_BLACK, curses.COLOR_BLACK)
    curses.init_pair(3, curses.COLOR_YELLOW, curses.COLOR_BLACK)
    stdscr.clear()
    curses.curs_set(0)
    curses.noecho()
    curses.cbreak()
    stdscr.keypad(True)
    stdscr.nodelay(True)

    pieces_foler = arguments.pieces_folder if arguments.pieces_folder else 'pieces'
    game_loop(arguments.is_log_set, pieces_foler, arguments.speed, width, height)

    curses.curs_set(1)
    curses.echo()
    curses.nocbreak()
    stdscr.keypad(False)

curses.wrapper(main)
